### ISSUE TITLE
composer.json or instructions missing?

### ISSUE THREAD

**Issue by mvaljento** [carlosas/full-docker-for-symfony-3#7]
I was trying to install everything per instructions, but there is no composer.json to install composer with. Is there a step missing from the setup instructions, where you actually install the Symfony 4 framework?

Because if you then try to run the Symfony installer in the www/symfony folder the installer will complain that the folder is not empty (there's a created "var" folder already there). Or should the symfony project be setup BEFORE installing the docker components?

**Comment by carlosas** [comment]
Hello @mvaljento 
This stack is built to work apart of your symfony project. You actually need to create a Symfony project wherever you want in your system and configure its path in the *.env* file, so when you run the stack, your folder is mapped inside the containers automatically.
